Repository milieuinfo/webcomponent-vl-ui-body, pull requests merged in 2020-07, with the labels that each got.

#8 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#9 Introductie nieuw Vlaanderen icon font
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/style.scss
  test/docker-compose.yml
Labels: bug

#10 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
